[project]
name = "hat-gui"
version = "0.6.4"
description = "Hat GUI"
readme = "README.rst"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "appdirs ~= 1.4.4",
    "hat-aio ~= 0.7.8",
    "hat-event ~= 0.8.8",
    "hat-json ~= 0.5.19",
    "hat-juggler ~= 0.6.11",
    "hat-monitor ~= 0.7.2",
    "hat-util ~= 0.6.10",
]

[project.urls]
Homepage = "http://hat-open.com"
Repository = "https://github.com/hat-open/hat-gui.git"
Documentation = "http://hat-gui.hat-open.com"

[project.optional-dependencies]
dev = [
    "hat-doit ~=0.14.5",
    "psutil >= 5.9.5",
    "sphinxcontrib-plantuml >= 0.24.1",
    "sphinxcontrib-programoutput >= 0.17",
]

[build-system]
requires = ["hat-doit ~=0.14.5"]
build-backend = "hat.doit.pep517"

[tool.hat-doit]
pytest_profile_dir = "build/profile"

[tool.pytest.ini_options]
testpaths = ["test_pytest"]
asyncio_mode = "auto"
timeout = 300

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
include = ["src_py/*"]
data_file = "build/.coverage"
